# Site settings
title: "Max Waine"
email: contact@mwaine.com
description: "Student coder."
baseurl: ""
url: "http://mwaine.com/"
title_description: "This site provides a working portfolio and blogging platform for myself. If you wish to see my portfolio  or search through my blog posts then open the sidebar on the left."
title_image: "https://avatars1.githubusercontent.com/u/5298767?v=3&s=466"
google_analytics: "UA-84601634-1"
disqus_account: mwaine-com
github_repository: https://github.com/Altazimuth/Altazimuth.github.io
post_limit: 5

# Social usernames/URLs
twitter_username: AltazimuthEE
github_username:  Altazimuth

# Footer
footer_left: "Made by Max Waine using <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson's</a> Carte Noire theme"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/Altazimuth/Altazimuth.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

collections:
  portfolio:
    output: true
    values:
      layout: portfolio
